# -*- mode: ruby -*- 
# vi: set ft=ruby :

BOX_IMAGE = "bento/ubuntu-20.04"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |x|    
    config.vm.define "web#{x}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "web#{x}"
      subconfig.vm.network :private_network, ip: "192.168.56.#{x + 10}"     
      # subconfig.vm.provision :shell, path: "web_bootstrap.sh"
      subconfig.vm.provision "shell", inline: <<-Web
        sudo -i   
        apt update && apt install -y apache2 keepalived
        echo web#{x} > /var/www/html/index.html
        systemctl enable apache2 keepalived
        systemctl start apache2 keepalived
      Web
      if (subconfig.vm.hostname=="web1") then
        subconfig.vm.provision "file", source: "./keepalived_master.conf", destination: "~/keepalived.conf"
        subconfig.vm.provision "shell", inline: <<-W1     
          sudo cp /home/vagrant/keepalived.conf /etc/keepalived/keepalived.conf
        W1
      else
        subconfig.vm.provision "file", source: "./keepalived_backup.conf", destination: "~/keepalived.conf"
        subconfig.vm.provision "shell", inline: <<-W2
          sudo cp /home/vagrant/keepalived.conf /etc/keepalived/keepalived.conf
        W2
      end
      subconfig.vm.provision "shell", inline: <<-W3
        sudo systemctl restart apache2 keepalived
      W3
    end
  end

  # copy ssh public key to the VM and update then reboot
  config.vm.provision "file", source: "./me.pub", destination: "~/.ssh/me.pub"  
  config.vm.provision "shell", inline: <<-SHELL     
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
 SHELL
end