---
all:
  children:
    cts:
      hosts:
        web01:
          ansible_host: 10.18.34.11
        db01:
          ansible_host: 10.18.34.12

    vms:
      hosts:
        k8s-node01:
          ansible_host: 10.18.34.21
        k8s-node02:
          ansible_host: 10.18.34.22
